---
- name: Install and Configure WireGuard
  hosts: all
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install WireGuard
      apt:
        name: wireguard
        state: present

    - name: Ensure WireGuard directory exists
      file:
        path: /etc/wireguard
        state: directory
        owner: root
        group: root
        mode: 0750

    - name: Generate server private key
      command: wg genkey
      register: wg_genkey
      changed_when: false

    - name: Set server private key
      copy:
        content: "{{ wg_genkey.stdout }}"
        dest: /etc/wireguard/privatekey
        owner: root
        group: root
        mode: 0600

    - name: Generate server public key
      command: wg pubkey
      args:
        stdin: "{{ wg_genkey.stdout }}"
      register: wg_genpubkey
      changed_when: false

    - name: Generate WireGuard configuration for server
      template:
        src: wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 0600

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: Verify WireGuard status
      command: wg show
      register: wg_status

    - name: Output WireGuard status
      debug:
        var: wg_status.stdout_lines
