---
- name: Install and Configure WireGuard
  hosts: all
  become: yes
  vars:
    wg_interface: "wg0"
    wg_port: "51820"
    wg_server_private_key: "your_server_private_key"
    wg_server_public_key: "your_server_public_key"
    wg_client_public_key: "your_client_public_key"
    wg_client_ip: "10.0.0.2/32"
    wg_server_ip: "10.0.0.1/24"

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install WireGuard
      apt:
        name: wireguard
        state: present

    - name: Ensure WireGuard directory exists
      file:
        path: /etc/wireguard
        state: directory
        owner: root
        group: root
        mode: 0750

    - name: Generate WireGuard configuration
      template:
        src: wg0.conf.j2
        dest: /etc/wireguard/{{ wg_interface }}.conf
        owner: root
        group: root
        mode: 0600

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@{{ wg_interface }}
        enabled: yes
        state: started

    - name: Verify WireGuard status
      command: wg show
      register: wg_status

    - name: Output WireGuard status
      debug:
        var: wg_status.stdout_lines
